// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlzql_7YtaBO3FSb0YmzqetNDeL7hdAKk',
    appId: '1:379569986225:web:86898498fa489139086090',
    messagingSenderId: '379569986225',
    projectId: 'midtermppb',
    authDomain: 'midtermppb.firebaseapp.com',
    storageBucket: 'midtermppb.firebasestorage.app',
    measurementId: 'G-2X0S2HND4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuZ0nUx_Lz-Anrlb1M2QrMI7nlproEVmU',
    appId: '1:379569986225:android:fa244c3146d62536086090',
    messagingSenderId: '379569986225',
    projectId: 'midtermppb',
    storageBucket: 'midtermppb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQuwBrClus4paALOIzs77Gg7-zDcuMVOE',
    appId: '1:379569986225:ios:105de08df3213ff3086090',
    messagingSenderId: '379569986225',
    projectId: 'midtermppb',
    storageBucket: 'midtermppb.firebasestorage.app',
    iosClientId: '379569986225-03p27n6evdfh62v1ivh01dkiajcc1rvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQuwBrClus4paALOIzs77Gg7-zDcuMVOE',
    appId: '1:379569986225:ios:105de08df3213ff3086090',
    messagingSenderId: '379569986225',
    projectId: 'midtermppb',
    storageBucket: 'midtermppb.firebasestorage.app',
    iosClientId: '379569986225-03p27n6evdfh62v1ivh01dkiajcc1rvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlzql_7YtaBO3FSb0YmzqetNDeL7hdAKk',
    appId: '1:379569986225:web:4e8e11259b403415086090',
    messagingSenderId: '379569986225',
    projectId: 'midtermppb',
    authDomain: 'midtermppb.firebaseapp.com',
    storageBucket: 'midtermppb.firebasestorage.app',
    measurementId: 'G-EKZ5LB296W',
  );
}
